version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo Installing app dependencies...
      - yarn install
  build:
    commands:
      - echo Building static site...
      - yarn build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
